shallow_clone: true
version: '{branch}-{build}'
cache:
  - C:\projects\qutebrowser\.cache
build: off
environment:
    PYTHONUNBUFFERED: 1
    PYTHON: C:\Python37-x64\python.exe
    matrix:
    - TESTENV: py37-pyqt513
    # - TESTENV: pylint

init:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - '%PYTHON% -m pip install -U pip'
  - '%PYTHON% -m pip install -r misc\requirements\requirements-tox.txt'
  - 'set PATH=C:\Python37-x64;%PATH'

test_script:
  - '%PYTHON% -m tox -e %TESTENV%'
